<div class="card-body">
  <div class="buttons">
  <a href="{{ route('eproc.perusahaan.administrasi.edit', ['user_id' => Crypt::encrypt(Auth::id())]) }}" class="btn btn-secondary {{ str_contains(Route::currentRouteName(), 'eproc.perusahaan.administrasi') ? 'btn-primary' : '' }}">Administrasi</a>
  <a href="{{ route('eproc.perusahaan.akta-pendirian-perusahaan.index', ['user_id' => Crypt::encrypt(Auth::id())]) }}" class="btn btn-secondary {{ str_contains(Route::currentRouteName(), 'eproc.perusahaan.akta-pendirian-perusahaan') ? 'btn-primary' : '' }}">Akta Pendirian Usaha</a>
  <a href="{{ route('eproc.perusahaan.pengurus-badan-usaha.index', ['user_id' => Crypt::encrypt(Auth::id())]) }}" class="btn btn-secondary {{ str_contains(Route::currentRouteName(), 'eproc.perusahaan.pengurus-badan-usaha') ? 'btn-primary' : '' }}">Pengurus Badan Usaha</a>
  <a href="{{ route('eproc.perusahaan.tanda-daftar-usaha.edit', ['user_id' => Crypt::encrypt(Auth::id())]) }}" class="btn btn-secondary {{ str_contains(Route::currentRouteName(), 'eproc.perusahaan.tanda-daftar-usaha') ? 'btn-primary' : '' }}">Tanda Daftar Usaha</a>
  <a href="{{ route('eproc.perusahaan.susunan-kepemilikan-saham.index', ['user_id' => Crypt::encrypt(Auth::id())]) }}" class="btn btn-secondary {{ str_contains(Route::currentRouteName(), 'eproc.perusahaan.susunan-kepemilikan-saham') ? 'btn-primary' : '' }}">Susunan Kepemilikan Saham</a>
  <a href="{{ route('eproc.perusahaan.data-personalia.index', ['user_id' => Crypt::encrypt(Auth::id())]) }}" class="btn btn-secondary {{ str_contains(Route::currentRouteName(), 'eproc.perusahaan.data-personalia') ? 'btn-primary' : '' }}">Data Personalia</a>
  <a href="{{ route('eproc.perusahaan.data-fasilitas.index', ['user_id' => Crypt::encrypt(Auth::id())]) }}" class="btn btn-secondary {{ str_contains(Route::currentRouteName(), 'eproc.perusahaan.data-fasilitas') ? 'btn-primary' : '' }}">Data Fasilitas</a>
  <a href="{{ route('eproc.perusahaan.pengalaman-perusahaan.index', ['user_id' => Crypt::encrypt(Auth::id())]) }}" class="btn btn-secondary {{ str_contains(Route::currentRouteName(), 'eproc.perusahaan.pengalaman-perusahaan') ? 'btn-primary' : '' }}">Pengalaman Perusahaan</a>
  <a href="{{ route('eproc.perusahaan.pekerjaan-yang-sedang-dilaksanakan.index', ['user_id' => Crypt::encrypt(Auth::id())]) }}" class="btn btn-secondary {{ str_contains(Route::currentRouteName(), 'eproc.perusahaan.pekerjaan-yang-sedang-dilaksanakan') ? 'btn-primary' : '' }}">Pekerjaan Yang Sedang Dilaksanakan</a>
  <a href="{{ route('eproc.perusahaan.sisa-kemampuan-nyata.edit', ['user_id' => Crypt::encrypt(Auth::id())]) }}" class="btn btn-secondary {{ str_contains(Route::currentRouteName(), 'eproc.perusahaan.sisa-kemampuan-nyata') ? 'btn-primary' : '' }}">Pekerjaan Yang Sedang Dilaksanakan</a>
  <a href="{{ route('eproc.perusahaan.lampiran-kualifikasi.edit', ['user_id' => Crypt::encrypt(Auth::id())]) }}" class="btn btn-secondary {{ str_contains(Route::currentRouteName(), 'eproc.perusahaan.lampiran-kualifikasi') ? 'btn-primary' : '' }}">Lampiran kualifikasi</a>
  </div>
</div>